"""Terminal-friendly glyphs per tool category — makes the event log skimmable."""
TOOL_ICONS = {
    "read_file": "≡", "read_document": "≣", "write_file": "✚", "edit_file": "✎", "multi_edit": "✎",
    "list_dir": "▣", "run_bash": "⚡", "search_code": "◎",
    "glob_files": "◇", "rank_files": "◆",
    "resolve_context": "✦", "read_bundle": "▤",
    "git_status": "⬡", "git_diff": "∆",
    "git_log": "∥",
    "launch_app": "▸", "focus_app": "❯", "quit_app": "✕",
    "list_apps": "☰", "frontmost_app": "⌂", "applescript": "⌘",
    "read_ui": "▒", "click_element": "↟", "wait": "⟳",
    "check_permissions": "⬟", "type_text": "⌨", "key_press": "⌨",
    "click_menu": "☰", "click_at": "⊕",
    "clipboard_get": "☐", "clipboard_set": "☑",
    "open_url": "⌗", "notify": "⚐", "speck": "♪",
    "shortcut_run": "⚙", "mac_control": "⚙",
    "powershell": "⌘", "task_run": "⚙", "system_control": "⚙",
    "web_search": "◎", "fetch_url": "⌗", "verified_search": "✦",
    "memory_save": "◆", "memory_list": "◆", "memory_delete": "✕",
    "read_image_text": "▣", "read_images_text": "▣",
    "ask_user_question": "?",
    "run_bg": "&", "bg_output": "&", "bg_kill": "✕",
    "screenshot": "◩",
    "schedule_wakeup": "⟳",
}
